version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/jars
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 300
  AfterInstall:
    - location: fix_previleges.sh
      timeout: 300
  ApplicationStart:
    - location: server_start.sh
      timeout: 20
  ApplicationStop:
    - location: server_stop.sh
      timeout: 20