spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://project.c1x0fbf8ort1.us-east-2.rds.amazonaws.com:3306/white_jotter?serverTimezone=UTC
    username: root
    password: Zxcv569692?
    hikari:
      connection-timeout: 30000
      minimum-idle: 3
      maximum-pool-size: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 1MB
  redis:
    host: localhost
    port: 6379
    timeout: 2000
  data:
    redis:
      repositories:
        enabled: false
logging:
  level:
    root: warn
    com.donald: info